Document: text-to-cad-common
Title: Debian text-to-cad-common Manual
Author: <insert document author here>
Abstract: This manual describes what text-to-cad-common is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/text-to-cad-common/text-to-cad-common.sgml.gz

Format: postscript
Files: /usr/share/doc/text-to-cad-common/text-to-cad-common.ps.gz

Format: text
Files: /usr/share/doc/text-to-cad-common/text-to-cad-common.text.gz

Format: HTML
Index: /usr/share/doc/text-to-cad-common/html/index.html
Files: /usr/share/doc/text-to-cad-common/html/*.html
