Document: training-data-generation
Title: Debian training-data-generation Manual
Author: <insert document author here>
Abstract: This manual describes what training-data-generation is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/training-data-generation/training-data-generation.sgml.gz

Format: postscript
Files: /usr/share/doc/training-data-generation/training-data-generation.ps.gz

Format: text
Files: /usr/share/doc/training-data-generation/training-data-generation.text.gz

Format: HTML
Index: /usr/share/doc/training-data-generation/html/index.html
Files: /usr/share/doc/training-data-generation/html/*.html
