Document: generative-cad
Title: Debian generative-cad Manual
Author: <insert document author here>
Abstract: This manual describes what generative-cad is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/generative-cad/generative-cad.sgml.gz

Format: postscript
Files: /usr/share/doc/generative-cad/generative-cad.ps.gz

Format: text
Files: /usr/share/doc/generative-cad/generative-cad.text.gz

Format: HTML
Index: /usr/share/doc/generative-cad/html/index.html
Files: /usr/share/doc/generative-cad/html/*.html
