Document: model-generation
Title: Debian model-generation Manual
Author: <insert document author here>
Abstract: This manual describes what model-generation is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/model-generation/model-generation.sgml.gz

Format: postscript
Files: /usr/share/doc/model-generation/model-generation.ps.gz

Format: text
Files: /usr/share/doc/model-generation/model-generation.text.gz

Format: HTML
Index: /usr/share/doc/model-generation/html/index.html
Files: /usr/share/doc/model-generation/html/*.html
