Document: text-to-cad
Title: Debian text-to-cad Manual
Author: <insert document author here>
Abstract: This manual describes what text-to-cad is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/text-to-cad/text-to-cad.sgml.gz

Format: postscript
Files: /usr/share/doc/text-to-cad/text-to-cad.ps.gz

Format: text
Files: /usr/share/doc/text-to-cad/text-to-cad.text.gz

Format: HTML
Index: /usr/share/doc/text-to-cad/html/index.html
Files: /usr/share/doc/text-to-cad/html/*.html
