#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-training-data-generation 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p python3-training-data-generation  || true
fi

# End automatically added section
